# Generated by Django 5.2 on 2025-06-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0003_subcard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcard',
            name='link',
        ),
        migrations.AddField(
            model_name='subcard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='subcard_images/'),
        ),
    ]
