# Generated by Django 5.2 on 2025-06-08 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0004_remove_subcard_link_subcard_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='name',
            new_name='event',
        ),
    ]
